### ISSUE TITLE
error -s it still working

### ISSUE THREAD

**Issue by Pradeepm98** [manudeobs/Akamai-2.0-Deobfuscator#1]
evalmachine.<anonymous>:1
O6["p\\5\x12"]()
              ^

TypeError: O6.p\5 is not a function
    at evalmachine.<anonymous>:1:15
    at Script.runInContext (node:vm:141:12)
    at Object.runInContext (node:vm:291:6)
    at CallExpression (C:\Users\hp\Documents\GitHub\Akamai-2.0-Deobfuscator\visitors\utils.js:43:54)       
    at NodePath._call (C:\Users\hp\Documents\GitHub\Akamai-2.0-Deobfuscator\node_modules\@babel\traverse\lib\path\context.js:45:20)
    at NodePath.call (C:\Users\hp\Documents\GitHub\Akamai-2.0-Deobfuscator\node_modules\@babel\traverse\lib\path\context.js:35:17)
    at NodePath.visit (C:\Users\hp\Documents\GitHub\Akamai-2.0-Deobfuscator\node_modules\@babel\traverse\lib\path\context.js:81:31)
    at TraversalContext.visitQueue (C:\Users\hp\Documents\GitHub\Akamai-2.0-Deobfuscator\node_modules\@babel\traverse\lib\context.js:86:16)
    at TraversalContext.visitMultiple (C:\Users\hp\Documents\GitHub\Akamai-2.0-Deobfuscator\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\hp\Documents\GitHub\Akamai-2.0-Deobfuscator\node_modules\@babel\traverse\lib\context.js:107:19)

Node.js v18.16.0

**Comment by ten4dinosaur** [comment]
It's because of string_concealing.js/findDecoderArrayId. U can try mine [fork](https://github.com/ten4dinosaur/Akamai-2.0-Deobfuscator)
